### ISSUE TITLE
Issues during Setup/Installation

### ISSUE THREAD

**Issue by gracchen** [CPJKU/score_following_game#19]
Hi, I am a UCLA piano major and I came across this score following game and found it very interesting so I want to set it all up.

I was wondering if you have tested the game on a Windows system and if so, how recently? If not, what about Linux? 

Thank you.

**Comment by stefan-balke** [comment]
Hi @gracchen and thanks for reaching out.
Windows might not be an option, we strongly recommend using Linux.
Ideally, you would need a GPU to run this. It is definitely more a research study than something to be used for fun.
However, if you would like to use this to experiment with the techniques, let us know.

Best,
Stefan

**Comment by gracchen** [comment]
Hi, Stefan! Thanks for letting me know. 
I've just tried setting the project up on a native Linux PC, and for creating the environment, both conda and pip returned errors (conda error output below). The issues involve python 3.6 and pytorch 1.3.1:

```
(base) thefox@thefoxmachine:~/Desktop/score_following_game$ conda env create -f environment.yml
Channels:
 - pytorch
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - pytorch
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package setuptools-39.2.0-py27_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.14.3  is installable with the potential options
│  ├─ numpy 1.14.3 would require
│  │  └─ numpy-base [1.14.3 py27h0ea5e3f_1|1.14.3 py35h0ea5e3f_1|1.14.3 py36h0ea5e3f_1], which requires
│  │     └─ blas * openblas, which can be installed;
│  ├─ numpy 1.14.3 would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  ├─ numpy 1.14.3 would require
│  │  └─ python >=3.5,<3.6.0a0 , which can be installed;
│  └─ numpy 1.14.3 would require
│     └─ numpy-base 1.14.3 py36h9be14a7_1, which requires
│        └─ mkl >=2018.0.2,<2019.0a0 , which can be installed;
├─ python 3.6**  is not installable because it conflicts with any installable versions previously reported;
├─ pytorch 1.3.1**  is not installable because it requires
│  ├─ blas 1.0 mkl, which conflicts with any installable versions previously reported;
│  └─ mkl >=2019.4,<2021.0a0 , which conflicts with any installable versions previously reported;
└─ setuptools 39.2.0  is installable with the potential options
   ├─ setuptools 39.2.0 would require
   │  └─ python >=2.7,<2.8.0a0 , which can be installed;
   ├─ setuptools 39.2.0 would require
   │  └─ python >=3.5,<3.6.0a0 , which can be installed;
   ├─ setuptools 39.2.0 would require
   │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   └─ setuptools 39.2.0 would require
      └─ python >=3.7,<3.8.0a0 , which can be installed.
```

To get around this, I:

1. manually install python 3.6 in a fresh conda env and activate it
	conda create --name score_following python=3.6
        conda activate score_following
2. manually install pytorch 1.3.1 in that env: 
	conda install pytorch=1.3.1 -c pytorch
3. add rest of the yml file: 
	by first removing python 3.6 and pytorch 1.3.1 from the environment.yml file, then running:
	conda env update --file environment.yml --prune

Which succeeded. And afterwards I verify that python is 3.6 and import torch's __version__ is 1.3.1. 

So then I proceed with the setup instructions (running the "python setup.py develop --user", installing fluidsynth, baselines and its dependencies like atari, ROM, ffmpeg, and passing all their pytests)

But when I try to run the very first test_agent.py  command in the readme to verify the game is working, it's as if pytorch had disappeared from the environment (ModuleNotFound). And when I try to install it again within the environment, it now shows pretty much the same errors as the conda env create -f environment.yml command did (below). So I am guessing I didn't address the root cause of the initial problem, and would greatly appreciate any guidance as to what the issue is. I've been stuck at just the setup for awhile...

```
(score_following) thefox@thefoxmachine:~/Desktop/score_following_game/score_following_game$ python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
>>> exit()
(score_following) thefox@thefoxmachine:~/Desktop/score_following_game/score_following_game$ conda install pytorch=1.3.1 -c pytorch
Channels:
 - pytorch
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package scipy-1.1.0-py36hd20e5f9_0 requires mkl >=2018.0.3,<2019.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.14.3  is installable with the potential options
│  ├─ numpy 1.14.3 would require
│  │  └─ numpy-base 1.14.3 py36h0ea5e3f_1, which requires
│  │     └─ blas * openblas, which can be installed;
│  ├─ numpy 1.14.3 would require
│  │  └─ numpy-base 1.14.3 py36h9be14a7_1, which requires
│  │     └─ mkl >=2018.0.2,<2019.0a0 , which can be installed;
│  ├─ numpy 1.14.3 would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  └─ numpy 1.14.3 would require
│     └─ python >=3.5,<3.6.0a0 , which can be installed;
├─ pin-1 is not installable because it requires
│  └─ python 3.6.* , which conflicts with any installable versions previously reported;
├─ pytorch 1.3.1**  is installable with the potential options
│  ├─ pytorch 1.3.1 would require
│  │  ├─ blas 1.0 mkl, which conflicts with any installable versions previously reported;
│  │  └─ mkl >=2019.4,<2021.0a0 , which conflicts with any installable versions previously reported;
│  ├─ pytorch 1.3.1 would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  └─ pytorch 1.3.1 would require
│     └─ python >=3.7,<3.8.0a0 , which can be installed;
└─ scipy 1.1.0  is installable with the potential options
   ├─ scipy 1.1.0 would require
   │  └─ mkl >=2018.0.2,<2019.0a0 , which can be installed;
   ├─ scipy 1.1.0 would require
   │  └─ mkl >=2018.0.3,<2019.0a0 , which can be installed;
   ├─ scipy 1.1.0 would require
   │  └─ python >=2.7,<2.8.0a0 , which can be installed;
   ├─ scipy 1.1.0 would require
   │  └─ python >=3.5,<3.6.0a0 , which can be installed;
   ├─ scipy 1.1.0 would require
   │  └─ blas [* openblas|1.0 openblas], which can be installed;
   ├─ scipy 1.1.0 would require
   │  ├─ blas 1.0 mkl, which conflicts with any installable versions previously reported;
   │  └─ mkl >=2019.1,<2021.0a0 , which conflicts with any installable versions previously reported;
   └─ scipy 1.1.0 would require
      └─ python >=3.7,<3.8.0a0 , which can be installed.
```

**Comment by stefan-balke** [comment]
Hi Grace,

your start looks promising. I hope the last hiccups can be resolved.

Could you provide a `conda list` in the score-following env?

**Comment by stefan-balke** [comment]
Maybe @fhenkel has also some ideas.

**Comment by gracchen** [comment]
Thanks for getting back to me. Here is the list:
```
(score_following) thefox@thefoxmachine:~/Desktop/score_following_game$ conda list
# packages in environment at /home/thefox/anaconda3/envs/score_following:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
atari-py                  0.2.9                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
baselines                 0.1.6                     dev_0    <develop>
blas                      1.0                         mkl  
ca-certificates           2024.3.11            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.5.30        py36h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               1.2.2                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.28.3           py36h14c3975_0  
dataclasses               0.8                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
decorator                 5.1.1                    pypi_0    pypi
expat                     2.5.0                h6a678d5_0  
filelock                  3.4.1                    pypi_0    pypi
fontconfig                2.14.1               h52c9d5c_1  
freetype                  2.12.1               h4a9f257_0  
future                    1.0.0                    pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
glib                      2.69.1               h4ff587b_1  
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.48.2                   pypi_0    pypi
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
gym                       0.15.4                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.6                      pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2022.1.0          h9e868ea_3769  
joblib                    1.1.1                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py36h2531618_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.39               h5eee18b_0  
librosa                   0.6.3                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.9.14               h74e7548_0  
llvmlite                  0.36.0                   pypi_0    pypi
madmom                    0.15.1                   pypi_0    pypi
markdown                  3.3.7                    pypi_0    pypi
matplotlib                2.2.2            py36hb69df0a_2  
mido                      1.2.10                   pypi_0    pypi
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h4414c95_1  
mock                      2.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nose                      1.3.7                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             3.4.3.18                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pandas                    0.25.3           py36he6710b0_0  
patsy                     0.5.1                    py36_0  
pbr                       6.0.0                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py36h06a4308_0  
pluggy                    1.0.0                    pypi_0    pypi
pretty-midi               0.2.8                    pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pyaudio                   0.2.11                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyfluidsynth              1.2.5                    pypi_0    pypi
pyglet                    1.3.2                    pypi_0    pypi
pynput                    1.3.7                    pypi_0    pypi
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py36h05f1152_2  
pysoundfile               0.9.0.post1              pypi_0    pypi
pytest                    7.0.1                    pypi_0    pypi
python                    3.6.13               h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-xlib               0.33                     pypi_0    pypi
pytz                      2021.3             pyhd3eb1b0_0  
pyyaml                    5.1.2            py36h7b6447c_0  
qt                        5.9.7                h5867ecd_1  
readline                  8.2                  h5eee18b_0  
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
resampy                   0.4.3                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.1.0            py36hd20e5f9_0  
seaborn                   0.8.1                    py36_0  
setuptools                59.6.0                   pypi_0    pypi
sip                       4.19.8           py36hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
statsmodels               0.10.1           py36hdd07704_0  
tbb                       2021.8.0             hdb19cb5_0  
tbb4py                    2021.3.0         py36hd09550d_0  
tensorboard               2.0.2                    pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     1.2.3                    pypi_0    pypi
tornado                   6.1              py36h27cfd23_0  
tqdm                      4.23.4                   py36_0  
typing-extensions         4.1.1                    pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
yaml                      0.1.7                had09818_2  
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

**Comment by fhenkel** [comment]
I just tried to set it up on an Ubuntu machine and also experienced some errors with the environment.
As a workaround I did the following:
1. Remove the pytorch dependency (`pytorch=1.3.1`) from the `environment.yml` file
2. install the environment `conda env create -f environment.yml`
3. Activate the environment and manually pip install pytorch `pip install torch==1.3.1`
I'm not sure what's going on with conda, but hopefully that works for you as well.

In case you encounter this error: `ModuleNotFoundError: No module named 'numba.decorators'`
You can go ahead and install a newer version of librosa. I think that shouldn't have a negative impact.

**Comment by gracchen** [comment]
Thank you, that did fix the pytorch. 

Unfortunately, I'm back at the reason why I asked the OS compatability question in the first place - when I tried initially on windows, I got errors regarding fluidsynth, and now with the fully setup environment, running test_agent.py shows these errors again (see below)

This repo's readme didn't specify which version of fluidsynth to install and the latest version probably doesn't support some features anymore, hence the "fluid_synth_get_channel_info" not found error. I think I read somewhere that this info method was removed in version 2, so I spent hours back then trying to install fluidsynth 1.1.11 by compiling it from their source code (they do not have executables for really old versions anymore) with no luck. I downloaded the zip src code for 1.1.11 release and tried 'cmake .." in that folder but it just caused more errors about packages not being found, etc. which kept snowballing.

I am aware this is going beyond your code and to fluidsynth at this point, but I would really appreciate it if you had any pointers on how to proceed next. 

```
(score_following) thefox@thefoxmachine:~/Desktop/score_following_game/score_following_game$ python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type human 
Traceback (most recent call last):
  File "test_agent.py", line 14, in <module>
    from score_following_game.data_processing.data_pools import get_single_song_pool
  File "/home/thefox/Desktop/score_following_game/score_following_game/data_processing/data_pools.py", line 8, in <module>
    from score_following_game.data_processing.data_production import SongCache
  File "/home/thefox/Desktop/score_following_game/score_following_game/data_processing/data_production.py", line 11, in <module>
    from score_following_game.data_processing.song import create_song
  File "/home/thefox/Desktop/score_following_game/score_following_game/data_processing/song.py", line 4, in <module>
    import pretty_midi as pm
  File "/home/thefox/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/__init__.py", line 138, in <module>
    from .pretty_midi import *
  File "/home/thefox/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py", line 15, in <module>
    from .instrument import Instrument
  File "/home/thefox/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/instrument.py", line 6, in <module>
    import fluidsynth
  File "/home/thefox/anaconda3/envs/score_following/lib/python3.6/site-packages/fluidsynth.py", line 180, in <module>
    ('info', POINTER(fluid_synth_channel_info_t), 1))
  File "/home/thefox/anaconda3/envs/score_following/lib/python3.6/site-packages/fluidsynth.py", line 53, in cfunc
    return CFUNCTYPE(result, *atypes)((name, _fl), tuple(aflags))
AttributeError: /lib/x86_64-linux-gnu/libfluidsynth.so.3: undefined symbol: fluid_synth_get_channel_info
```

The version of fluidsynth I have:
```
(score_following) thefox@thefoxmachine:~/Downloads/fluidsynth-1.1.11/build$ fluidsynth --version
FluidSynth runtime version 2.2.5
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.2.5
Sample type=double
```

**Comment by fhenkel** [comment]
When I installed Fluidsynth yesterday on an Ubuntu machine I simply ran `sudo apt-get install fluidsynth` and didn't have any issue. That's the version that got installed

```
FluidSynth version 1.1.9
Copyright (C) 2000-2018 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of E-mu Systems, Inc.

FluidSynth 1.1.9
```

**Comment by gracchen** [comment]
Thank you so much! I got everything working now! Since apt-get didn't find any version below 2, I installed these two debs: [FluidSynth 1.1.11](https://answers.launchpad.net/ubuntu/focal/amd64/fluidsynth/1.1.11-4ubuntu1) and [libfluidsynth 1.1.11](https://answers.launchpad.net/ubuntu/focal/amd64/libfluidsynth1/1.1.11-4ubuntu1)
