### ISSUE TITLE
Wav file not found

### ISSUE THREAD

**Issue by weefeen** [CPJKU/score_following_game#4]
I am trying to configure the repo on Windows 10. I have Anaconda installed. Baselines installed Fluidsynth installed but somehow I am receving and error while running the test command. Wav file in temp folder not found 

-----------------------------------StackTrace-----------------------------
D:\softwareanaconda\envs\score_following\lib\site-packages\pretty_midi\pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
The system cannot find the path specified.
Traceback (most recent call last):
  File "test_agent.py", line 58, in <module>
    dict(config=config, song_name=args.piece, directory=args.data_set, real_perf=args.real_perf))
  File "d:\zz - perso\weefeen\engineering\development\07 - scripts\recognition\score\score_following_game\data_processing\data_pools.py", line 319, in get_single_song_pool
    song = load_song(config, cur_path_score, cur_path_perf, real_perf=real_perf)
  File "d:\zz - perso\weefeen\engineering\development\07 - scripts\recognition\score\score_following_game\data_processing\song.py", line 346, in load_song
    sound_font_default_path=sound_font_default_path)
  File "d:\zz - perso\weefeen\engineering\development\07 - scripts\recognition\score\score_following_game\data_processing\song.py", line 242, in __init__
    sound_font_path=self.sound_font_default_path)
  File "d:\zz - perso\weefeen\engineering\development\07 - scripts\recognition\score\score_following_game\data_processing\song.py", line 79, in prepare_perf_representation
    representation = self.spec_processing(midi, self.spectrogram_params, sound_font_path=sound_font_path)
  File "d:\zz - perso\weefeen\engineering\development\07 - scripts\recognition\score\score_following_game\data_processing\utils.py", line 172, in midi_to_spec_otf
    spec = processor.process(audio_path).T
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\processors.py", line 336, in process
    data = _process((processor, data, kwargs))
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\processors.py", line 200, in _process
    return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\processors.py", line 128, in __call__
    return self.process(*args, **kwargs)
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\audio\signal.py", line 909, in process
    return Signal(data, **args)
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\audio\signal.py", line 743, in __new__
    dtype=dtype)
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\audio\signal.py", line 610, in load_audio_file
    stop=stop, dtype=dtype)
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\madmom\audio\signal.py", line 496, in load_wave_file
    file_sample_rate, signal = wavfile.read(filename, mmap=True)
  File "D:\softwareanaconda\envs\score_following\lib\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\msmabq\\AppData\\Local\\Temp\\1581692342.5371628.wav'

**Comment by fhenkel** [comment]
Does the error occur after some files where already loaded properly or immediately in the beginning?

**Comment by weefeen** [comment]
Hi,

immediately in the beginning.

at the example:

python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type human 

Thanks

**Comment by fhenkel** [comment]
The code was primarily tested on Linux and Mac, but I will try to reproduce the problem as soon as possible on a Windows machine.

**Comment by weefeen** [comment]
I appreciate, thank you!

**Comment by gszswork** [comment]
I just met the same error, and I'm sure the file '1596094087.714646.wav' exists under folder 'tmp', I met this both in ubuntu 18.04 and Mac 10.15. So can you share how did you solve this error? I guess that's a problem with madam but I didn't find any solutions online.
`/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
Traceback (most recent call last):
  File "test_agent.py", line 58, in <module>
    dict(config=config, song_name=args.piece, directory=args.data_set, real_perf=args.real_perf))
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/data_pools.py", line 319, in get_single_song_pool
    song = load_song(config, cur_path_score, cur_path_perf, real_perf=real_perf)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 344, in load_song
    sound_font_default_path=sound_font_default_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 242, in __init__
    sound_font_path=self.sound_font_default_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 79, in prepare_perf_representation
    representation = self.spec_processing(midi, self.spectrogram_params, sound_font_path=sound_font_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/utils.py", line 172, in midi_to_spec_otf
    spec = processor.process(audio_path).T
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 336, in process
    data = _process((processor, data, kwargs))
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 200, in _process
    return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 128, in __call__
    return self.process(*args, **kwargs)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 909, in process
    return Signal(data, **args)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 743, in __new__
    dtype=dtype)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 631, in load_audio_file
    raise LoadAudioFileError(error)
madmom.audio.signal.LoadAudioFileError: "All attempts to load audio file '/tmp/1596094087.714646.wav' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."
`

**Comment by fhenkel** [comment]
@gszswork Could you please try to load an existing wav file with madmom to see if it is only a problem with this package.
Do you have ffmpeg  installed as suggested in the error message?

**Comment by fhenkel** [comment]
@weefeen sorry for the very late reply, the last couple of months were quite busy. I'm currently setting up a Windows 10 VM to reproduce the error.

**Comment by gszswork** [comment]
the ffmpeg is already installed. 
I just did a test, in anaconda(python3.6.10) I ran the test command and there is the error, but if I just run the madmom's load_audio_file function, the wav file can be loaded. as follows: 

`(score_following) szdeMacBook-Pro:score_following_game szg$ python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type optimal 
/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
Traceback (most recent call last):
  File "test_agent.py", line 58, in <module>
    dict(config=config, song_name=args.piece, directory=args.data_set, real_perf=args.real_perf))
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/data_pools.py", line 319, in get_single_song_pool
    song = load_song(config, cur_path_score, cur_path_perf, real_perf=real_perf)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 344, in load_song
    sound_font_default_path=sound_font_default_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 242, in __init__
    sound_font_path=self.sound_font_default_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 79, in prepare_perf_representation
    representation = self.spec_processing(midi, self.spectrogram_params, sound_font_path=sound_font_path)
  File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/utils.py", line 172, in midi_to_spec_otf
    spec = processor.process(audio_path).T
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 336, in process
    data = _process((processor, data, kwargs))
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 200, in _process
    return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 128, in __call__
    return self.process(*args, **kwargs)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 909, in process
    return Signal(data, **args)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 743, in __new__
    dtype=dtype)
  File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 631, in load_audio_file
    raise LoadAudioFileError(error)
madmom.audio.signal.LoadAudioFileError: "All attempts to load audio file '/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."
(score_following) szdeMacBook-Pro:score_following_game szg$ python 
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import madmom
>>> test = madmom.audio.signal.load_audio_file('/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav')
>>> print(test)
(memmap([[  0,   0],
        [  0,   0],
        [  0,   0],
        ...,
        [183, 221],
        [193, 231],
        [201, 238]], dtype=int16), 44100)
>>> 

`

**Comment by fhenkel** [comment]
Maybe thats a problem with access rights on Mac, my colleague added this note in the readme.
"Important: If you are a MAC user you have to add your terminal application (e.g. iTerm) to the list of accessibility input devices (system control -> security & privacy -> accessibility)."
Does this fix the issue?

**Comment by fhenkel** [comment]
@weefeen Regarding the Windows problem.
1) Please make sure that the sound-font file is properly extracted in the sound_fonts folder (it seems that this is only done automatically on linux when i run setup.py)
2) I made a mistake in the config files (mutopia_lchs1.yaml). The path for the sound fonts are encoded in linux format and you should change 'sound_fonts/grand-piano-YDP-20160804.sf2'  to 'sound_fonts\grand-piano-YDP-20160804.sf2' if you want to use it on Windows.

These were the easy fixes. Unfortunately there is a more severe problem with respect to fluidsynth on windows. Apparently the pretty_midi package that I use does not support the latest fluidsynth (>=2.x), which means one hast to built and older version from the sources. I found compiled versions [here](https://github.com/JoshuaPrzyborowski/FluidSynth-Windows-Builds), but they do not work in my case. If this is not a very pressing issue for you anymore, I would really appreciate if I do not have to build everything from scratch and possibly encounter many more errors along the way. But maybe you have a better suggestion.

**Comment by YiBenjing456** [comment]
> the ffmpeg is already installed.
> I just did a test, in anaconda(python3.6.10) I ran the test command and there is the error, but if I just run the madmom's load_audio_file function, the wav file can be loaded. as follows:
> 
> `(score_following) szdeMacBook-Pro:score_following_game szg$ python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type optimal
> /Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py💯 RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks. This is not a valid type 0 or type 1 MIDI file. Tempo, Key or Time Signature may be wrong.
> RuntimeWarning)
> fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
> Traceback (most recent call last):
> File "test_agent.py", line 58, in
> dict(config=config, song_name=args.piece, directory=args.data_set, real_perf=args.real_perf))
> File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/data_pools.py", line 319, in get_single_song_pool
> song = load_song(config, cur_path_score, cur_path_perf, real_perf=real_perf)
> File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 344, in load_song
> sound_font_default_path=sound_font_default_path)
> File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 242, in **init**
> sound_font_path=self.sound_font_default_path)
> File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 79, in prepare_perf_representation
> representation = self.spec_processing(midi, self.spectrogram_params, sound_font_path=sound_font_path)
> File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/utils.py", line 172, in midi_to_spec_otf
> spec = processor.process(audio_path).T
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 336, in process
> data = _process((processor, data, kwargs))
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 200, in _process
> return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 128, in **call**
> return self.process(*args, **kwargs)
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 909, in process
> return Signal(data, **args)
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 743, in **new**
> dtype=dtype)
> File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 631, in load_audio_file
> raise LoadAudioFileError(error)
> madmom.audio.signal.LoadAudioFileError: "All attempts to load audio file '/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."
> (score_following) szdeMacBook-Pro:score_following_game szg$ python
> Python 3.6.10 |Anaconda, Inc.| (default, May 7 2020, 23:06:31)
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import madmom
> > > > test = madmom.audio.signal.load_audio_file('/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav')
> > > > print(test)
> > > > (memmap([[  0,   0],
> > > > [  0,   0],
> > > > [  0,   0],
> > > > ...,
> > > > [183, 221],
> > > > [193, 231],
> > > > [201, 238]], dtype=int16), 44100)
> 
> `

Hi, did you fix this problem? I face the same problem now.

**Comment by fhenkel** [comment]
@YiBenjing456 are you also using macOS?

**Comment by gszswork** [comment]
> > the ffmpeg is already installed.
> > I just did a test, in anaconda(python3.6.10) I ran the test command and there is the error, but if I just run the madmom's load_audio_file function, the wav file can be loaded. as follows:
> > `(score_following) szdeMacBook-Pro:score_following_game szg$ python test_agent.py --data_set ./data/test_sample --piece Anonymous__lesgraces__lesgraces --game_config game_configs/mutopia_lchs1.yaml --agent_type optimal
> > /Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/pretty_midi/pretty_midi.py100 RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks. This is not a valid type 0 or type 1 MIDI file. Tempo, Key or Time Signature may be wrong.
> > RuntimeWarning)
> > fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
> > Traceback (most recent call last):
> > File "test_agent.py", line 58, in
> > dict(config=config, song_name=args.piece, directory=args.data_set, real_perf=args.real_perf))
> > File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/data_pools.py", line 319, in get_single_song_pool
> > song = load_song(config, cur_path_score, cur_path_perf, real_perf=real_perf)
> > File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 344, in load_song
> > sound_font_default_path=sound_font_default_path)
> > File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 242, in **init**
> > sound_font_path=self.sound_font_default_path)
> > File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/song.py", line 79, in prepare_perf_representation
> > representation = self.spec_processing(midi, self.spectrogram_params, sound_font_path=sound_font_path)
> > File "/Users/szg/Downloads/score_following_game-tismir-2019/score_following_game/data_processing/utils.py", line 172, in midi_to_spec_otf
> > spec = processor.process(audio_path).T
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 336, in process
> > data = _process((processor, data, kwargs))
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 200, in _process
> > return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/processors.py", line 128, in **call**
> > return self.process(*args, **kwargs)
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 909, in process
> > return Signal(data, **args)
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 743, in **new**
> > dtype=dtype)
> > File "/Users/szg/anaconda3/envs/score_following/lib/python3.6/site-packages/madmom/audio/signal.py", line 631, in load_audio_file
> > raise LoadAudioFileError(error)
> > madmom.audio.signal.LoadAudioFileError: "All attempts to load audio file '/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."
> > (score_following) szdeMacBook-Pro:score_following_game szg$ python
> > Python 3.6.10 |Anaconda, Inc.| (default, May 7 2020, 23:06:31)
> > [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> > Type "help", "copyright", "credits" or "license" for more information.
> > > > > import madmom
> > > > > test = madmom.audio.signal.load_audio_file('/var/folders/79/26vt9yzn6w15mqnqw7x2l9fw0000gn/T/1596098055.943209.wav')
> > > > > print(test)
> > > > > (memmap([[  0,   0],
> > > > > [  0,   0],
> > > > > [  0,   0],
> > > > > ...,
> > > > > [183, 221],
> > > > > [193, 231],
> > > > > [201, 238]], dtype=int16), 44100)
> > 
> > 
> > `
> 
> Hi, did you fix this problem? I face the same problem now.

Yes I fixed it.
In ubuntu 20.04 and Python 3.7, after installing ffmpeg it runs perfectly.
